version: 2.1
orbs:
  autify-for-mobile: autify/mobile@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

jobs:
  integration-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - autify-for-mobile/run_test_plan:
          test_plan_id: ${INTEGRATION_TEST_TEST_PLAN_ID}
          build_id: ${INTEGRATION_TEST_BUILD_ID}
      - run:
          name: Make sure the response is saved
          command: cat response-mobile-run-test-plan.txt
      - run:
          name: Download app files
          command: |
            readonly APP_ZIP_FILE="https://github.com/autifyhq/public-testing-assets/raw/main/mobile/ios/ci-sample.zip"
            curl -L -o "./ci-sample.zip" $APP_ZIP_FILE
            unzip ./ci-sample.zip -d ./app_dir
      - autify-for-mobile/upload_build:
          autify_project_id: ${INTEGRATION_TEST_PROJECT_ID}
          autify_upload_token: ${INTEGRATION_TEST_UPLOAD_TOKEN}
          autify_app_dir_path: "./app_dir/ci-sample.app/"


workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - integration-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: autify/mobile
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
